name: Dev CI

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7.4.2-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 3306:3306

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Make application.properties
        run: |
          mkdir -p ./src/main/resources
          echo "toss.client-key=${{ secrets.TOSS_CLIENT_KEY }}" >> ./src/main/resources/application.properties
          echo "toss.secret-key=${{ secrets.TOSS_SECRET_KEY }}" >> ./src/main/resources/application.properties
          echo "jwt.secret.key=${{ secrets.JWT_SECRET_KEY }}" >> ./src/main/resources/application.properties
          echo "spring.redis.host=redis" >> ./src/main/resources/application.properties
          echo "spring.redis.port=6379" >> ./src/main/resources/application.properties
          echo "spring.datasource.url=jdbc:mysql://localhost:3306/testdb" >> ./src/main/resources/application.properties
          echo "spring.datasource.username=testuser" >> ./src/main/resources/application.properties
          echo "spring.datasource.password=testpass" >> ./src/main/resources/application.properties
          echo "spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver" >> ./src/main/resources/application.properties
          echo "spring.jpa.hibernate.ddl-auto=update" >> ./src/main/resources/application.properties
          echo "spring.jpa.show-sql=true" >> ./src/main/resources/application.properties

      - name: Build Project
        run: ./gradlew clean build -x test
